### ISSUE TITLE
Support Firebase certificate store for verifying the tokens

### ISSUE THREAD

**Issue by sberyozkin** [smallrye/smallrye-jwt#382]
[Firebase certificate store](https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com) uses a JSON format which is a map between what appears to be a certificate thumbprint and the certificate; 
We've had a 2nd user query about the firebase token authentication in Quarkus.
smallrye-jwt already provides an option to resolve the certificates for the token resolution by expecting to match a cert thumbprint against one of the certificates - so it should straightforward enough to support the Firebase store format

**Comment by sirfak** [comment]
putting the error logs here if it helps


_2021-01-14 21:57:08,732 DEBUG [io.qua.sma.jwt.run.aut.MpJwtValidator] (vert.x-eventloop-thread-0) Authentication failed: io.smallrye.jwt.auth.principal.ParseException: Failed to verify a token
        at io.smallrye.jwt.auth.principal.DefaultJWTTokenParser.parse(DefaultJWTTokenParser.java:123)
        at io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator$1.accept(MpJwtValidator.java:59)
        at io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator$1.accept(MpJwtValidator.java:55)
        at io.smallrye.mutiny.operators.UniCreateWithEmitter.subscribing(UniCreateWithEmitter.java:22)
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
        at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
        at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.lambda$subscribing$0(ContextPropagationUniInterceptor.java:51)
        at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:215)
        at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.subscribing(ContextPropagationUniInterceptor.java:51)  
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
        at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
        at io.smallrye.mutiny.operators.UniFlatMapOnItem.subscribing(UniFlatMapOnItem.java:56)
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
        at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
        at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.lambda$subscribing$0(ContextPropagationUniInterceptor.java:51)
        at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:215)
        at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.subscribing(ContextPropagationUniInterceptor.java:51)  
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
        at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
        at io.smallrye.mutiny.operators.UniFlatMapOnItem.subscribing(UniFlatMapOnItem.java:56)
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
        at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
        at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.lambda$subscribing$0(ContextPropagationUniInterceptor.java:51)
        at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:215)
        at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.subscribing(ContextPropagationUniInterceptor.java:51)  
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
        at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
        at io.smallrye.mutiny.operators.UniFlatMapOnItem.subscribing(UniFlatMapOnItem.java:56)
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
        at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
        at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.lambda$subscribing$0(ContextPropagationUniInterceptor.java:51)
        at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:215)
        at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.subscribing(ContextPropagationUniInterceptor.java:51)  
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
        at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
        at io.smallrye.mutiny.operators.UniOnEventConsume.subscribing(UniOnEventConsume.java:23)
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
        at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
        at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.lambda$subscribing$0(ContextPropagationUniInterceptor.java:51)
        at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:215)
        at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.subscribing(ContextPropagationUniInterceptor.java:51)  
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
        at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
        at io.smallrye.mutiny.operators.UniOnEventConsume.subscribing(UniOnEventConsume.java:23)
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
        at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
        at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.lambda$subscribing$0(ContextPropagationUniInterceptor.java:51)
        at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:215)
        at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.subscribing(ContextPropagationUniInterceptor.java:51)  
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
        at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
        at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:69)
        at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:129)
        at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:45)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:130)
        at io.quarkus.vertx.http.runtime.cors.CORSFilter.handle(CORSFilter.java:80)
        at io.quarkus.vertx.http.runtime.cors.CORSFilter.handle(CORSFilter.java:17)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:130)
        at io.quarkus.vertx.http.runtime.devmode.VertxHotReplacementSetup.handleHotReplacementRequest(VertxHotReplacementSetup.java:39)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:130)
        at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:54)
        at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:36)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$7.handle(VertxHttpRecorder.java:334)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$7.handle(VertxHttpRecorder.java:331)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:112)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:103)
        at io.quarkus.vertx.http.runtime.devmode.VertxHotReplacementSetup$2.handle(VertxHotReplacementSetup.java:72)
        at io.quarkus.vertx.http.runtime.devmode.VertxHotReplacementSetup$2.handle(VertxHotReplacementSetup.java:63)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:330)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.jose4j.jwt.consumer.InvalidJwtException: JWT processing failed. Additional details: [[17] Unable to process JOSE 
object (cause: org.jose4j.lang.UnresolvableKeyException: Failed to load a key from https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com): JsonWebSignature{"alg":"RS256"}->eyJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJodHRwczovL2lkZW50aXR5dG9vbGtpdC5nb29nbGVhcGlzLmNvbS9nb29nbGUuaWRlbnRpdHkuaWRlbnRpdHl0b29sa2l0LnYxLklkZW50aXR5VG9vbGtpdCIsImV4cCI6MTYxMDYyNTExOCwiaWF0IjoxNjEwNjIxNTE4LCJpc3MiOiJmaXJlYmFzZS1hZG1pbnNkay1rYTNqY0BwaXBpbGlrYS04YWY0MC5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsInN1YiI6ImZpcmViYXNlLWFkbWluc2RrLWthM2pjQHBpcGlsaWthLThhZjQwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwidWlkIjoid0tOVjNqa0lwR2E2VU9Dd0ZPVldUdFFxRXdsMiJ9.dxcNf4z9juCzr3GWa2QndoM7MfF2w0raO1iPU_op69pnAuc2FuYvZy5_zf5lhJDgFCSX9mJi-pzpRgF9HROzc3Xw7eJH6my04lqKTPoBR5FHQkWskltuwuI-n7V0dOsuGd2-TlJyMXo2V8OtqbWVPvBoe1ziRrnWXFZ6AZWv-7A-C4i4YEfWgOZad_xaR_5GVUgzu9f6YJQTbr0iX1l1uExNO2hQOYR7qXKTQHSOUCs-fmG78tAoO_Rpm19WnJo3Im1YBVf1jBiGpyjTwTJw1iann2aBwjYO5WoyTTE1EybVvnLkoJW5VyG1SZTFpGMRY7lCz9NZydzg5MjIDKc4uQ]
        at org.jose4j.jwt.consumer.JwtConsumer.processContext(JwtConsumer.java:271)
        at org.jose4j.jwt.consumer.JwtConsumer.process(JwtConsumer.java:433)
        at io.smallrye.jwt.auth.principal.DefaultJWTTokenParser.parse(DefaultJWTTokenParser.java:90)
        ... 95 more
Caused by: org.jose4j.lang.UnresolvableKeyException: Failed to load a key from https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com
        at io.smallrye.jwt.auth.principal.KeyLocationResolver.resolveKey(KeyLocationResolver.java:110)
        at org.jose4j.jwt.consumer.JwtConsumer.processContext(JwtConsumer.java:213)
        ... 97 more_

**Comment by sberyozkin** [comment]
See also https://firebase.google.com/docs/auth/admin/verify-id-tokens#verify_id_tokens_using_a_third-party_jwt_library

**Comment by sberyozkin** [comment]
@sirfak FYI, the token in the stacktrace has no `kid` so supporting a key store format from https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com will not help in your case - but only for valid ID tokens such as those shown in https://stackoverflow.com/a/71096804/1133928

**Comment by sberyozkin** [comment]
Oh, that stack trace contains an answer, just point to a Firebase JWK store format :
https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com.

Closing this issue now
