### ISSUE TITLE
Producer method return type not found in index: javax.json.JsonObject

### ISSUE THREAD

**Issue by tomwetjens** [smallrye/smallrye-jwt#539]
After upgrading Quarkus to 2.5.3, the application fails to startup because javax.json is no longer on the class path as it is replaced with jakarta.json.

One of the offending classes is io.smallrye.jwt.auth.cdi.JsonValueProducer. There might be other classes that import javax.json.
The imports should be replaced with jakarta.json.

Application startup fails with error message:
```
2021-12-16 21:36:52,433 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#registerBeans threw an exception: java.lang.IllegalArgumentException: Producer method return type not found in index: javax.json.JsonObject
	at io.quarkus.arc.processor.Types.getProducerMethodTypeClosure(Types.java:245)
	at io.quarkus.arc.processor.Beans.createProducerMethod(Beans.java:236)
	at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:1020)
	at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:233)
	at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:120)
	at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:380)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:832)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:330)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:93)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:456)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:67)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:149)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:105)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:145)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:63)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#registerBeans threw an exception: java.lang.IllegalArgumentException: Producer method return type not found in index: javax.json.JsonObject
	at io.quarkus.arc.processor.Types.getProducerMethodTypeClosure(Types.java:245)
	at io.quarkus.arc.processor.Beans.createProducerMethod(Beans.java:236)
	at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:1020)
	at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:233)
	at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:120)
	at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:380)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:832)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.builder.Execution.run(Execution.java:116)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:161)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:328)
	... 9 more
Caused by: java.lang.IllegalArgumentException: Producer method return type not found in index: javax.json.JsonObject
	at io.quarkus.arc.processor.Types.getProducerMethodTypeClosure(Types.java:245)
	at io.quarkus.arc.processor.Beans.createProducerMethod(Beans.java:236)
	at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:1020)
	at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:233)
	at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:120)
	at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:380)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:832)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

Possible workaround to at least get the server started:
`quarkus.arc.exclude-types=io.smallrye.jwt.auth.cdi.JsonValueProducer`

**Comment by radcortez** [comment]
Hi @tomwetjens 

This sounds really strange because neither SR JWT nor Quarkus moved to the `jakarta` namespace. I'm wondering if you have something else in the classpath that is overriding the `javax` one?

Are you able to provide a reproducer? Thank you

**Comment by tomwetjens** [comment]
As I was trying to create a reproducer from the quickstart, I found out that somehow through parent POMs, the version of org.glassfish:jakarta.json was managed to 2.0.1, whereas quarkus comes with 1.1.6. The former has the jakarta.json classes and the latter still has the javax.json classes. 

Removing this version override did the trick to make it work!
