### ISSUE TITLE
Error while using `smalrye.jwt.sign.key.location` properties with file: scheme

### ISSUE THREAD

**Issue by mcruzdev** [smallrye/smallrye-jwt#746]
I have an application using quarkus-jwt with the following configurations:

```properties
mp.jwt.verify.publickey.location=file:/keys/privateKey.pem
```

The file is on `/keys/' directory.

With this configuration I am receiving the following error:

```bash
2023-11-12 16:22:21,400 INFO  [io.quarkus] (main) condomind-api 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.5.0) started in 2.953s. Listening on: http://0.0.0.0:8080
2023-11-12 16:22:21,401 INFO  [io.quarkus] (main) Profile prod activated. 
2023-11-12 16:22:21,401 INFO  [io.quarkus] (main) Installed features: [agroal, amazon-ses, cdi, hibernate-orm, hibernate-orm-panache, hibernate-validator, jdbc-mysql, narayana-jta, qute, resteasy-reactive, resteasy-reactive-jackson, resteasy-reactive-qute, security, smallrye-context-propagation, smallrye-jwt, smallrye-openapi, vertx]
2023-11-12 16:22:28,844 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /auth/sign-in failed, error id: caf298a0-ac90-4ec7-aabb-5400a63c14f9-1: io.smallrye.jwt.build.JwtSignatureException: SRJWT05009: 
        at io.smallrye.jwt.build.impl.JwtSignatureImpl.sign(JwtSignatureImpl.java:105)
        at com.github.mcruzdev.infrastructure.security.JwtAdapter.generate(JwtAdapter.java:17)
        at com.github.mcruzdev.application.usecases.auth.Login.execute(Login.java:28)
        at com.github.mcruzdev.application.usecases.auth.Login_ClientProxy.execute(Unknown Source)
        at com.github.mcruzdev.presentation.resources.AuthResource.signIn(AuthResource.java:60)
        at com.github.mcruzdev.presentation.resources.AuthResource$quarkusrestinvoker$signIn_a406def941aac544eb675e8bd55eaf7594b3a996.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "java.io.InputStream.read(byte[])" because "is" is null
        at io.smallrye.jwt.util.ResourceUtils.readBytes(ResourceUtils.java:93)
        at io.smallrye.jwt.build.impl.JwtSignatureImpl.sign(JwtSignatureImpl.java:82)
        ... 15 more
``` 

I do not know but the error can starts from [here](https://github.com/smallrye/smallrye-jwt/blob/66a74d5e0b4cdf58977d9d3968d0354404625d13/implementation/common/src/main/java/io/smallrye/jwt/util/ResourceUtils.java#L73)

**Comment by sberyozkin** [comment]
@mcruzdev `/keys/privateKey.pem` should work, right now, if the `file:` is available, it is not stripped before being passed to the file input stream

**Comment by mcruzdev** [comment]
Hi @sberyozkin TY for the comment.

I changed to `/keys/privateKey.pem` and I am receiving it:

```bash
Caused by: java.net.MalformedURLException: no protocol: /keys/privateKey.pem
```

**Comment by mcruzdev** [comment]
Hi @sberyozkin this error occurs because the file permission!

I removed `USER 185` declaration from Quarkus Dockerfile.legacy-jar and it works now, TY!

**Comment by sberyozkin** [comment]
@mcruzdev Hi,

>Was necessary to use another image and remove USER 185 declaration from Quarkus Dockerfile.legacy-jar and it works now.

Do you think it is a Quarkus bug ? If yes, please open a Quarkus issue.

I'll get this `file:` issue fixed here too

**Comment by sberyozkin** [comment]
@mcruzdev Can you please try `mp.jwt.verify.publickey.location=file:./keys/privateKey.pem` ?

I've created a simple test:
```
String path = "src/test/resources/privateKey.pem";
        File file = new File(path);
        String absolutePath = file.getAbsolutePath();
        String jwt = Jwt.claims() .sign("file:" + absolutePath);
```

and it works

**Comment by mcruzdev** [comment]
Hi @sberyozkin
> Do you think it is a Quarkus bug ? If yes, please open a Quarkus issue.

> I'll get this file: issue fixed here too

I do not know if can be a Quarkus bug, what do you think? I think that it could be documented.

I will try this one: https://github.com/smallrye/smallrye-jwt/issues/746#issuecomment-1810783240

**Comment by sberyozkin** [comment]
@mcruzdev Sorry, PR tightening some checks have closed this issue. It includes a test using a file scheme.
IMHO it is not a smallrye-jwt issue that a file is not accessed in the docker image, I was thinking that may be some tweaks could be added to the way Quarkus Dockerfile.legacy-jar script, but it is not a smallrye-jwt issue.

**Comment by mcruzdev** [comment]
> @mcruzdev Sorry, PR tightening some checks have closed this issue. It includes a test using a file scheme. IMHO it is not a smallrye-jwt issue that a file is not accessed in the docker image, I was thinking that may be some tweaks could be added to the way Quarkus Dockerfile.legacy-jar script, but it is not a smallrye-jwt issue.

Hi @sberyozkin, sorry for delay... I agree with you, thank you very much for your support.
